### ISSUE TITLE
Upload/Link not working

### ISSUE THREAD

**Issue by tzoppa** [wayneschuller/strengthjourneys#1]
Hi there, have been looking for sometining like this all over the place and found the link on reddit
https://www.reddit.com/r/visualization/comments/vvm25/visualizinggraphing_workout_progress_over_time/

I can't get my data to upload, just keep getting an error message. Would love to know if this gets fixed though!

**Comment by wayneschuller** [comment]
hi, 

I'd love to help, can you say more about what happens?

**Comment by wayneschuller** [comment]
Can you share your gsheet with wayneschuller@gmail.com and I will try to help figure it out?

You could also try this dev deployment: https://strengthjourneys-git-main-wayneschuller.vercel.app/

If you press F12 to get your web browser dev console, you should see informative messages about what is happening in the dev build.

**Comment by tzoppa** [comment]
Thanks here's a copy of the sheet:

 Copy of Strength Journeys Data Format
<https://docs.google.com/spreadsheets/d/1fcBf7sAOBmbktKrGlWjmzQ9M2EUca7-dDbKlC0v3lOw/edit?usp=drive_web>

My original version has data all the way back to October and I also
initially had every cell filled in as that's how I had been recording it in
my own spreadsheet (all dates and all lift types filled out rather than
left blank). When I retried with the above sheet I got the same error.

[image: image.png]

best,
Tommy

**Comment by tzoppa** [comment]
FYI, same error happens when I try to upload your example sheet too

**Comment by wayneschuller** [comment]
Thank you @tzoppa - I have identified a problem uploading your file. 

There is some kind of issue with google permissions I think.

I'm very keen to get you as a user of the app and solve this problem.

Can you just confirm for me you have your google permissions setup properly?

Go to: https://myaccount.google.com/data-and-privacy

And click on: "Third-party apps and services"

And you should see "Strength Journeys" in the list?

Click on it and you should see something like this?

![image](https://github.com/wayneschuller/strengthjourneys/assets/1592295/86e27bd7-df57-4cbb-bf32-b65561cfdc2b)

If you don't see this, then try logging out and logging in again.

You can also try deleting "Strength Journeys" from your Google security page, then relogin to Strength Journeys and give permissions again, and try picking the file...

Let me know how you go!

**Comment by tzoppa** [comment]
Hi Wayne,

All permissions were correct and I deleted and reauthorized to try again
but same issue.

Something to note on both occasions when I go to upload the spreadsheets I
am unable to see the preview of them in the pop-up.
[image: image.png]

**Comment by tzoppa** [comment]
I also did a screen record and this screen appears for a flash before the
main screen reloads with the red bubble. But this doesn't look like it
corresponds to my data.

[image: adccd008-492c-402e-bc99-480353c761ea.png]

**Comment by wayneschuller** [comment]
hi @tzoppa - unfortunately your screen record and png are not showing here... can you recheck?

I'm a bit busy with life this week but I'm very keen to solve this issue...

**Comment by wayneschuller** [comment]
![image](https://github.com/wayneschuller/strengthjourneys/assets/1592295/a83e79ce-10e2-4773-802b-408a75f2ae84)

This is your data when it works! It loads in dev mode on my local machine but not on the public site - YET

**Comment by tzoppa** [comment]
Here's the screenshot.
[image](https://github.com/wayneschuller/strengthjourneys/assets/161237396/6e90035c-fd61-49ac-82ec-eb82b86df430)

Great thanks for your help.

**Comment by wayneschuller** [comment]
Update - yes that awful red dialog is my nightmare right now.

I am engaging with Google to get full approval for my app to have access to a google sheet that the user gives permission to.

Hopefully this will be fixed within the next few days.

For some reason Google allows this to work via local development builds but not to the general public - so I missed this problem in my testing so far.

So hopefully you are helping me solve a critical blockage that will allow anyone and everyone to use Strenth Journeys.

**Comment by wayneschuller** [comment]
@tzoppa - I think I have fixed the bug.

I discovered there was a missing Google environment variable (app id) which you have to pass into the google file picker for the drive.file scope to work.

Could you please test and confirm it works for you?

**Comment by tzoppa** [comment]
Looks like it's working for me. Thanks!

**Comment by wayneschuller** [comment]
That's fantastic news!

I'm going to do some work in the coming weeks to improve Strength Journeys.

Please let me know what you think would be useful for you to track your fitness progress?

**Comment by wayneschuller** [comment]
Fixed!
