### ISSUE TITLE
Metric Support (kg instead of lbs)

### ISSUE THREAD

**Issue by moritz-zls** [wayneschuller/strengthjourneys#2]
Relevant for the two pages:

1. Strength Visualizer
2. PR-Analyzer

The system currently always assumes lbs when i enter my lifts.

As a metric user, i would love if there could be a switch so these two pages could also show my logs in KG instead of lbs. Nothing fancy but would be great to share when sharing with others.

Thanks :-)

![image](https://github.com/wayneschuller/strengthjourneys/assets/31901005/c7386102-e613-4e39-9d91-fd245747b93c)

![image](https://github.com/wayneschuller/strengthjourneys/assets/31901005/d753c03b-6fe5-4672-860a-f18b7b2eaaf5)

**Comment by wayneschuller** [comment]
hi @moritz-zls !

In your google spreadsheet you need to specify kg in the weight column:
![image](https://github.com/wayneschuller/strengthjourneys/assets/1592295/3afc7723-185c-4919-8712-73a07849cbda)

I'm also in a metric country (Australia). 

If there is no specification of either lb or kg with the integer in the weight column, the code currently will default to pounds - for America first!

Maybe there is a better way to handle default systems.

Please let me know if you can get kg working ok. 

Also - did you really trap deadlift 170kg? That is quite heavy. Well done!

**Comment by wayneschuller** [comment]
I've added some better documentation to highlight the use of kg weights. I hope to add a feature to auto detect metric regions...
